// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvtdxbaodmcpnmjhlpjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52dGR4YmFvZG1jcG5tamhscGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTE3NDIsImV4cCI6MjA2MjIyNzc0Mn0.zzI6olXe-WTZc6zZ-ih9DbiVNxCI9tUTCl43ab2uHFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);